### ISSUE TITLE
Endpoint route değişiklikleri

### ISSUE THREAD

**Issue by Blind-Striker** [CodeFiction/codefiction-tech-lambda#5]
Podcast'leri getiren ve search eden endpoint'ler **/podcasts** altına taşındı. Böyle hem AWS Api Gateway  de yapılan "greedy path parameter" https://github.com/CodeFiction/codefiction-tech-lambda/issues/3 değişikliğinin çalışması sağlanacak hem de api başka amaçlarla da kullanılabilecek.

**Comment by onuar** [comment]
Geleceğe not: http://docs.aws.amazon.com/apigateway/latest/developerguide/amazon-api-gateway-using-stage-variables.html
